"""empty message

Revision ID: 438d3b72dc9b
Revises: eb3da253537c
Create Date: 2020-10-19 15:17:53.069074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438d3b72dc9b'
down_revision = 'eb3da253537c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'requests', ['requisition'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='unique')
    # ### end Alembic commands ###
